- name: added in 2.4, previously you used 'include'
  include: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
- include: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
- include: readme.yml