---
- hosts: jenkins*
  become: yes
  become_method: sudo

  vars_files:
    - vars.yml

  pre_tasks:  
    - name: Disable IPv6
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        reload: yes
      loop:
        - { name: net.ipv6.conf.all.disable_ipv6, value: 1 }
        - { name: net.ipv6.conf.default.disable_ipv6, value: 0 } 
        - { name: net.ipv6.conf.lo.disable_ipv6, value: 1 }
        
  roles:
    - geerlingguy.jenkins
    - geerlingguy.docker
  
  tasks:
    - name: Add user 'jenkins' to 'docker' group
      user:
        name: jenkins
        group: docker
    
    - name: restart jenkins
      service: name=jenkins state=restarted

    - name: Readme
      local_action: template
      args:
        src: "readme.j2"
        dest: "{{ drop_home }}/README"
        mode: '0644'
      run_once: true

