---
- hosts: jenkins*
  become: yes
  become_method: sudo

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.jenkins
    - geerlingguy.docker
  
  tasks:
    - name: Readme
      local_action: template
      args:
        src: "readme.j2"
        dest: "{{ drop_home }}/README"
        mode: '0644'
      run_once: true

